# Define apps we’re likely to install
def cask(name); dep name, :template => "icelab:cask"; end # Avoid repetition below

cask "1password"
cask "atext"
cask "caffeine"
cask "charles"
cask "cloak"
cask "dash"
cask "doxie"
cask "firefox"
dep "firefoxdeveloperedition", :template => "icelab:cask" do requires "icelab:homebrew tap".with "caskroom/versions" end
cask "google-chrome"
cask "handbrake"
cask "hazel"
cask "imagealpha"
cask "imageoptim"
cask "iterm2"
cask "launchbar"
cask "licecap"
cask "mailplane"
cask "openemu"
cask "postico"
cask "reveal"
cask "rowanj-gitx"
cask "skype"
cask "slack"
cask "spectacle"
cask "sublime-text"
cask "superduper"
cask "taskpaper"
cask "textexpander"
cask "tokens"
cask "transmission"
cask "transmit"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"